name: Build and Deploy to AKS

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Login to Azure
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Login to ACR
        run: az acr login --name acrstudelydesk

      - name: Build and Push Docker image
        run: |
          docker build -t acrstudelydesk.azurecr.io/flask-desk:0.0.1.RELEASE .
          docker push acrstudelydesk.azurecr.io/flask-desk:0.0.1.RELEASE


      - name: Set up kubectl context
        uses: azure/aks-set-context@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}
          cluster-name: aksstudelydesk
          resource-group: RG-STUDELY

      - name: Restart deployment
        run: |
          kubectl rollout restart deployment deployment-flaskdesk
